default_platform(:android)

platform :android do
  desc "Capture screenshots for store listings"
  lane :screenshots do
    build_android_app(
      task: "assembleDebug assembleAndroidTest"
    )
    screengrab
  end

  desc "Deploy a new version to the Google Play Store internal track"
  lane :deploy do
    build_android_app(
      task: "bundleRelease"
    )
    upload_to_play_store(
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: false,
      skip_upload_screenshots: false
    )
  end

  desc "Upload metadata and screenshots to the Google Play Store"
  lane :upload_metadata do
    upload_to_play_store(
      skip_upload_aab: true,
      skip_upload_apk: true,
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: false,
      skip_upload_screenshots: false
    )
  end
end
